### ISSUE TITLE
How to get it to work with .NETFramework,Version=v4.6.1

### ISSUE THREAD

**Issue by PizzaConsole** [tonysneed/hello-netcore-wpf-nano#1]
How would I get this to work with .NETFramework,Version=v4.6.1 ?

Meaning my Server project is a .net core 3.1 app, but it uses a class library that is .NETFramework,Version=v4.6.1...

**Comment by tonysneed** [comment]
What happens when you try to run your app on Nano server?

**Comment by PizzaConsole** [comment]
it gave me an error saying that .NETFramework,Version=v4.6.1 was not installed in the environment. But I migrated the projects to .net standard instead. problem solved
